#!/bin/sh -
# Sample startup script for mimsrv.
# MIMVIEW points to the build directory for the Polymer ui files.
# CONTENT points to the directory hierarchy containing the photos.
# PASSWD points to the file containing usernames and encrypted passwords.
# PORT is the TCP port number on which to listen for client connections.

HERE=$(dirname $0)

MIMVIEW=$HERE/_ui/build/default
CONTENT_SRC=$HERE/testdata/demo
CONTENT_TMP=$HERE/testdata/demo-tmp
PASSWD=$HERE/testdata/password-demo.txt
PORT=8021

cleanup() {
  rm -rf $CONTENT_TMP
}
cleanup
trap cleanup EXIT

# We copy the content demo to a tmp dir and run it there. This allows
# the user to edit the content without touching the original demo data.
cp -rp $CONTENT_SRC $CONTENT_TMP

./mimsrv --mimviewroot $MIMVIEW --contentroot $CONTENT_TMP \
    --passwordfile $PASSWD --maxclockskewseconds 20 --port $PORT
